# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a285bcb5dc3ec1a09b53a35730790a92501358dc51721a49893c89d6c296c0c3aa3984355f286f45d4565db57db18b45ecb71c2e3e95c77538321cc11d0d2cc

test:
  secret_key_base: f7c7a7808329bec0b34d82db86f8d6a5ee50bf48e6796e07385d66807ef78499d0a9398e5a091b8d5f16c24a76482a67aee4b04321b80f7094c6797d0909f7e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
